{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "oteemo.serviceAccountName" . }}
  labels:
{{ include "oteemo.labels" . | indent 4 }}
{{- end -}}
